### ISSUE TITLE
Problem with the training code

### ISSUE THREAD

**Issue by jiyuuchc** [dliu5812/PDAM#5]
Hi, trying to reproduce the results of this repo, but got the following error when running the top-level script (train_gn_pdam.sh)

```
Traceback (most recent call last):
  File "tools/train_net.py", line 206, in <module>
    main()
  File "tools/train_net.py", line 201, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 90, in train
    do_train(
  File "/home/FCAM/jyu/PDAM/maskrcnn_benchmark/engine/trainer.py", line 96, in do_train
    loss_dict = model(s_images, t_images, s_targets, grl_alpha, s_semgt)
  File "/home/FCAM/jyu/miniconda3/envs/pdam/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/FCAM/jyu/miniconda3/envs/pdam/lib/python3.8/site-packages/apex-0.1-py3.8-linux-x86_64.egg/apex/amp/_initialize.py", line 198, in new_fwd
    output = old_fwd(*applier(args, input_caster),
  File "/home/FCAM/jyu/PDAM/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 103, in forward
    = self.roi_heads(t_features, t_proposals, targets=None, is_source=False)
  File "/home/FCAM/jyu/miniconda3/envs/pdam/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/FCAM/jyu/PDAM/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 26, in forward
    x, detections, loss_box = self.box(features, proposals, targets, is_source)
  File "/home/FCAM/jyu/miniconda3/envs/pdam/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/FCAM/jyu/PDAM/maskrcnn_benchmark/modeling/roi_heads/box_head/box_head.py", line 56, in forward
    result, keep_list, keep_list2 = self.post_processor((class_logits, box_regression), proposals)
  File "/home/FCAM/jyu/miniconda3/envs/pdam/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/FCAM/jyu/PDAM/maskrcnn_benchmark/modeling/roi_heads/box_head/inference.py", line 84, in forward
    boxlist = boxlist.clip_to_image(remove_empty=False)
  File "/home/FCAM/jyu/PDAM/maskrcnn_benchmark/structures/bounding_box.py", line 216, in clip_to_image
    self.bbox[:, 0].clamp_(min=0, max=self.size[0] - TO_REMOVE)
RuntimeError: Output 0 of SelectBackward0 is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.
```

Any suggestions?

My environment is:

```
python                   3.8
torch                    1.10.0+cu111
torchaudio               0.10.0+rocm4.1
torchvision              0.11.0+cu111
```

**Comment by jiyuuchc** [comment]
Never mind. Figured it out. 

I guess the code probably worked in older version of torch. But it is a bit outdated. Here is a patch if you care:

```
diff --git a/maskrcnn_benchmark/structures/bounding_box.py b/maskrcnn_benchmark/structures/bounding_box.py
index 25791d5..dd72dbd 100644
--- a/maskrcnn_benchmark/structures/bounding_box.py
+++ b/maskrcnn_benchmark/structures/bounding_box.py
@@ -213,10 +213,12 @@ class BoxList(object):
 
     def clip_to_image(self, remove_empty=True):
         TO_REMOVE = 1
-        self.bbox[:, 0].clamp_(min=0, max=self.size[0] - TO_REMOVE)
-        self.bbox[:, 1].clamp_(min=0, max=self.size[1] - TO_REMOVE)
-        self.bbox[:, 2].clamp_(min=0, max=self.size[0] - TO_REMOVE)
-        self.bbox[:, 3].clamp_(min=0, max=self.size[1] - TO_REMOVE)
+        self.bbox = torch.stack([
+            torch.clamp(self.bbox[:, 0], min=0, max=self.size[0] - TO_REMOVE),
+            torch.clamp(self.bbox[:, 1], min=0, max=self.size[1] - TO_REMOVE),
+            torch.clamp(self.bbox[:, 2], min=0, max=self.size[0] - TO_REMOVE),
+            torch.clamp(self.bbox[:, 3], min=0, max=self.size[1] - TO_REMOVE),
+        ], axis=-1)
         if remove_empty:
             box = self.bbox
             keep = (box[:, 3] > box[:, 1]) & (box[:, 2] > box[:, 0])
```
